// <auto-generated />
using MergeMediaSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MergeMediaSite.Migrations
{
    [DbContext(typeof(ClassContext))]
    [Migration("20180506130253_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MergeMediaSite.Models.HostingTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cores");

                    b.Property<string>("Instance");

                    b.Property<string>("Prices");

                    b.Property<string>("Ram");

                    b.Property<string>("Storage");

                    b.HasKey("Id");

                    b.ToTable("HostingTables");
                });
#pragma warning restore 612, 618
        }
    }
}
